#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
runcmd:
  - logger "runcmd started"
  - mkdir -p /data
  - chown 
  - docker run -d -v /data:/data -e SERVERADMIN_PASSWORD=${ADMIN_PASSWORD} -e TS3SERVER_LICENSE=accept -p 9987:9987/udp -p 10011:10011 -p 30033:30033 --name=ts3-server aheil/teamspeak3-server
  - logger "runcmd finished"
